#!/bin/bash
#SINK=$( pactl list short sinks | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' | head -n 1 )
SINK=1
NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )
MUTED=$(pacmd list-sinks | awk '/muted/ { print $2 }' | head -n $(( $SINK + 1 )) | tail -n 1)

if [[ "$MUTED" = "no" ]]; then
	echo " $NOW%"
	echo " $NOW%"
	echo ""
else
	echo " (0%)"
	echo " (0%)"
	echo "#ffe863"
fi