#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

STATE=$(cat /sys/class/net/$INTERFACE/operstate)
if [[ "$STATE" == 'down' ]] || [[ "$STATE" == '' ]]; then
  echo ""
  echo ""
  echo ""
  exit 0
fi

# TODO eventually accept a -4 or -6 flag to force only one or the other
IPADDR=$(ip addr show $INTERFACE | perl -n -e '/inet ([^\/]+)/ && print $1')

if [ -z "$IPADDR" ]; then
  echo "-" # full text
  echo "-" # short text
  echo "#ffe863"
  exit 0
fi

OUTPUT="$IPADDR"
if [[ -d "/sys/class/net/$INTERFACE/wireless" ]]; then
    quality=$(grep ${INTERFACE} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    OUTPUT="($quality at $(/usr/sbin/iwgetid -r)) $OUTPUT"
fi


# full text
echo "$OUTPUT"
echo "$OUTPUT"
echo ""